"""Decompile the D3D9 shader-bind and draw paths to settle where the pixel
shader's r0 comes from.

The HLE UV export reads a *vertex shader export* register named by the pixel
shader's texture profile (s0<-r0). If Xenos PARAM_GEN is enabled for these
shaders, PS r0 is generated by the rasterizer, not interpolated from a VS
export, and reading the VS export is wrong by construction. SQ_PROGRAM_CNTL is
context register 0x2180, SQ_CONTEXT_MISC is 0x2181; the register file is written
through the D3D9 command-buffer macros, so the constants appear as immediates.

Run headless against a COPY of the IDB:
  idat.exe -A -S"tools/ida_dump_param_gen.py" <copy>.i64
"""

import ida_auto
import ida_bytes
import ida_funcs
import ida_hexrays
import ida_kernwin
import ida_pro
import idautils

TARGETS = [
    (0x825506E8, "D3DDevice_SetPixelShader"),
    (0x825508A8, "D3DDevice_SetVertexShader"),
    (0x825561B0, "D3DDevice_DrawVertices"),
    (0x825565C8, "D3DDevice_DrawIndexedVertices"),
    (0x82564C50, "PatchVertexShaderToMatchVertexDeclaration"),
]

# Register indices worth spotting as immediates in the decompilation. The
# command-buffer writes usually encode (reg - 0x2000) so both forms are listed.
INTERESTING = {
    0x2180: "SQ_PROGRAM_CNTL",
    0x0180: "SQ_PROGRAM_CNTL (0x2000-relative)",
    0x2181: "SQ_CONTEXT_MISC",
    0x0181: "SQ_CONTEXT_MISC (0x2000-relative)",
}


def emit(text):
    ida_kernwin.msg(str(text) + "\n")


def dump(ea, label):
    emit("")
    emit("===== 0x%08X %s =====" % (ea, label))
    func = ida_funcs.get_func(ea)
    if func is None:
        emit("no function object at this address (auto-analysis did not "
             "define one); dumping raw instructions instead")
        for off in range(0, 0x200, 4):
            emit("  0x%08X  %s" % (ea + off,
                                   ida_bytes.print_insn_mnem(ea + off)))
        return
    emit("range 0x%08X-0x%08X (%d bytes), name %s" % (
        func.start_ea, func.end_ea, func.end_ea - func.start_ea,
        ida_funcs.get_func_name(func.start_ea)))
    try:
        text = str(ida_hexrays.decompile(func.start_ea))
    except Exception as exc:
        emit("decompile failed: %s" % exc)
        return
    emit(text)
    hits = []
    for value, name in INTERESTING.items():
        for form in ("0x%X" % value, "%d" % value):
            if form in text:
                hits.append("%s as %s" % (name, form))
                break
    emit("--- register immediates present: %s ---" %
         (", ".join(hits) if hits else "none"))


def main():
    ida_auto.auto_wait()
    if not ida_hexrays.init_hexrays_plugin():
        emit("hexrays not available")
    for ea, label in TARGETS:
        dump(ea, label)


main()
ida_pro.qexit(0)
